### ISSUE TITLE
Make metamask snap launch ready

### ISSUE THREAD

**Issue by abheektripathy** [availproject/metamask-snap-avail#17]
working on these changes to get the snap ready for mainnet launch.

https://docs.google.com/document/d/1Oa171mVoMN8uurkVB7OF8dE_m78ZLOB1phE5lYn1Q00/edit#heading=h.g1wx42ndv3yy

**Comment by abheektripathy** [comment]
@vthunder after you review the snap once, this can be closed

**Comment by vthunder** [comment]
I believe this is done
