### ISSUE TITLE
Create design for Metamask Snap (Web-based Wallet)

### ISSUE THREAD

**Issue by vthunder** [availproject/metamask-snap-avail#4]
We have the basic functions of Metamask Snap working with Avail (list balance, send, receive, and a few less-used functions), but our UI is very much for testing only. We should have a Web design for a basic wallet. We can keep it simple. For inspiration, here is the Starknet Snap:

![Image](https://github.com/availproject/metamask-snap-avail/assets/435972/0d9fb29e-58f7-4020-80a0-518d8d0e8293)

The Avail snap will only support AVL transfers, so no need for the "add token" UI. But otherwise we should also have these basic functions:

- Displaying balance and account information (address)
- Send/receive
- Display past transactions
- Network switcher (Goldberg/mainnet in our case)

Not sure what we'd have in the hamburger menu, maybe we don't need it for now.

**Comment by cpp-phoenix** [comment]
This the Starknet snap link. It can help understand workflow of the snap.
https://snaps.consensys.io/starknet

**Comment by cpp-phoenix** [comment]
@abheektripathy If you haven't started working on it, You can assign it to me.

**Comment by cpp-phoenix** [comment]
@vthunder @abheektripathy Kindly review the designs.

https://www.figma.com/file/03bs8ccbT7nR1a8KTGTZJ6/Metamask-Avail-Snap-team-library?type=design&node-id=0%3A1&mode=design&t=5gQcjL32P2mcXtuv-1

**Comment by vthunder** [comment]
Mocks look great, thanks! No notes, let's implement

**Comment by vthunder** [comment]
Can you submit a PR and add these to the readme? Maybe add the main view as an image with a link to figma for the rest. That way we can get the PR to show up on OnlyDust.

**Comment by cpp-phoenix** [comment]
@vthunder Kindly review #6

**Comment by vthunder** [comment]
Thanks!
